layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 11
  exclude:
    archived: false
    forks: true
    projects: "-"
    # - repo-name

social_media:
  linkedin: https://www.linkedin.com/in/tahmeed-asaad-a04605120?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B7av4NhgtQRmbBzugexsevw%3D%3D
  website: https://tahmeed-asaad.github.io/-/
  facebook: https://www.facebook.com/tahmeedasaad/
  twitter: https://twitter.com/TahmeedAsaad
  
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: https://tahmeed-asaad.github.io/-/
  # youtube: your_username

topics:

  - name: Time Series Analysis
    web_url: https://towardsdatascience.com/the-complete-guide-to-time-series-analysis-and-forecasting-70d476bfe775
    image_url: https://camo.githubusercontent.com/d68e58faa96a0d4e7af3ae0c1c427dfbcac42ec73f05d7a2ecef99bf1543be45/68747470733a2f2f63312e736664637374617469632e636f6d2f636f6e74656e742f64616d2f626c6f67732f63612f426c6f67253230506f7374732f73616c65732d666f726563617374696e672d6865616465722e6a7067
   
  - name: Machine Learning
    web_url: https://www.sas.com/en_us/insights/analytics/machine-learning.html
    image_url: https://raw.githubusercontent.com/Tahmeed-Asaad/-/master/IMAGES/wp3205204-machine-learning-wallpapers.jpg

  - name: Database
    web_url: https://www.datanamic.com/support/lt-dez005-introduction-db-modeling.html
    image_url: https://raw.githubusercontent.com/Tahmeed-Asaad/-/master/IMAGES/wp2347547-database-wallpapers.jpg
  


